# Generated by scripts/generate_workload_policies.py; do not hand-edit.
# Identity: prometheus-openbao; environment: test; owner: observability-platform

path "codestra/data/test/observability/openbao/metrics-client/*" {
  capabilities = ["read"]
}

path "codestra/metadata/test/observability/openbao/metrics-client/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/development/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/development/*" {
  capabilities = ["deny"]
}

path "codestra/data/staging/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/staging/*" {
  capabilities = ["deny"]
}

path "codestra/data/production/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/production/*" {
  capabilities = ["deny"]
}

path "sys/metrics" {
  capabilities = ["read"]
}

path "auth/token/lookup-self" {
  capabilities = ["read"]
}

path "auth/token/renew-self" {
  capabilities = ["update"]
}

path "auth/token/revoke-self" {
  capabilities = ["update"]
}

path "database/*" {
  capabilities = ["deny"]
}

path "pki-*" {
  capabilities = ["deny"]
}

path "transit-*" {
  capabilities = ["deny"]
}

path "sys/*" {
  capabilities = ["deny"]
}

path "auth/token/create*" {
  capabilities = ["deny"]
}
