# Generated by scripts/mcr_contract.py; offline source only.
# Applying this policy requires separate runtime approval.
path "codestra/data/staging/middleware/api/tenants/example-tenant/providers/example-provider/callback-verification" {
  capabilities = ["read"]
}
