# Generated by scripts/mcr_contract.py; offline source only.
# Applying this policy requires separate runtime approval.
path "codestra/data/staging/middleware/worker/email/klyrow/tenants/example-tenant/providers/example-provider/adapter" {
  capabilities = ["read"]
}
