# Generated by scripts/mcr_contract.py; offline source only.
# Applying this policy requires separate runtime approval.
path "codestra/data/staging/n8n/middleware-client/tenants/example-tenant/clients/n8n-automation/targets/middleware/auth" {
  capabilities = ["read"]
}
