#!/usr/bin/env python3
"""Generate exact least-privilege HCL from the canonical workload authority."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUTHORITY = ROOT / "config/workload-secret-authority.v1.json"
OUTPUT = ROOT / "openbao/policies"
INDEX = ROOT / "config/policies/generated-policy-index.v1.json"
ENVIRONMENTS = ("development", "test", "staging", "production")


def policy_source(role: dict) -> str:
    environment = role["environment"]
    identity = role["serviceIdentity"]
    lines = [
        "# Generated by scripts/generate_workload_policies.py; do not hand-edit.",
        f"# Identity: {identity}; environment: {environment}; owner: {role['owner']}",
        "",
    ]
    for logical_prefix in role["pathPrefixes"]:
        relative = logical_prefix.removeprefix("codestra/")
        lines.extend(
            [
                f'path "codestra/data/{relative}*" {{',
                '  capabilities = ["read"]',
                "}",
                "",
                f'path "codestra/metadata/{relative}*" {{',
                '  capabilities = ["read", "list"]',
                "}",
                "",
            ]
        )
    for other in ENVIRONMENTS:
        if other == environment:
            continue
        lines.extend(
            [
                f'path "codestra/data/{other}/*" {{',
                '  capabilities = ["deny"]',
                "}",
                "",
                f'path "codestra/metadata/{other}/*" {{',
                '  capabilities = ["deny"]',
                "}",
                "",
            ]
        )
    if identity == "prometheus-openbao":
        lines.extend(
            [
                'path "sys/metrics" {',
                '  capabilities = ["read"]',
                "}",
                "",
            ]
        )
    lines.extend(
        [
            'path "auth/token/lookup-self" {',
            '  capabilities = ["read"]',
            "}",
            "",
            'path "auth/token/renew-self" {',
            '  capabilities = ["update"]',
            "}",
            "",
            'path "auth/token/revoke-self" {',
            '  capabilities = ["update"]',
            "}",
            "",
            'path "database/*" {',
            '  capabilities = ["deny"]',
            "}",
            "",
            'path "pki-*" {',
            '  capabilities = ["deny"]',
            "}",
            "",
            'path "transit-*" {',
            '  capabilities = ["deny"]',
            "}",
            "",
            'path "sys/*" {',
            '  capabilities = ["deny"]',
            "}",
            "",
            'path "auth/token/create*" {',
            '  capabilities = ["deny"]',
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def build(authority: dict) -> tuple[dict[Path, str], dict]:
    rendered = {}
    entries = []
    for role in authority["roles"]:
        relative = Path(role["environment"]) / f"{role['serviceIdentity']}.hcl"
        source = policy_source(role)
        rendered[relative] = source
        entries.append(
            {
                "environment": role["environment"],
                "serviceIdentity": role["serviceIdentity"],
                "policyName": f"workload-{role['serviceIdentity']}-{role['environment']}",
                "path": f"openbao/policies/{relative.as_posix()}",
                "sha256": hashlib.sha256(source.encode()).hexdigest(),
                "runtimeApplyAuthorized": False,
            }
        )
    index = {
        "schemaVersion": 1,
        "authority": "config/workload-secret-authority.v1.json",
        "runtimeApplyAuthorized": False,
        "policies": sorted(entries, key=lambda item: (item["environment"], item["serviceIdentity"])),
    }
    return rendered, index


def main() -> None:
    authority = json.loads(AUTHORITY.read_text(encoding="utf-8"))
    rendered, index = build(authority)
    expected_paths = {OUTPUT / relative for relative in rendered}
    stale = {
        path
        for environment in ENVIRONMENTS
        for path in (OUTPUT / environment).glob("*.hcl")
        if path not in expected_paths
    }
    if stale:
        raise SystemExit("stale generated policies: " + ",".join(str(path) for path in sorted(stale)))
    for relative, source in rendered.items():
        path = OUTPUT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
    INDEX.write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
