# Generated by scripts/generate_workload_policies.py; do not hand-edit.
# Identity: kong-gateway; environment: production; owner: platform-edge

path "codestra/data/production/kong/*" {
  capabilities = ["read"]
}

path "codestra/metadata/production/kong/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/development/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/development/*" {
  capabilities = ["deny"]
}

path "codestra/data/test/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/test/*" {
  capabilities = ["deny"]
}

path "codestra/data/staging/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/staging/*" {
  capabilities = ["deny"]
}

path "auth/token/lookup-self" {
  capabilities = ["read"]
}

path "auth/token/renew-self" {
  capabilities = ["update"]
}

path "auth/token/revoke-self" {
  capabilities = ["update"]
}

path "database/*" {
  capabilities = ["deny"]
}

path "pki-*" {
  capabilities = ["deny"]
}

path "transit-*" {
  capabilities = ["deny"]
}

path "sys/*" {
  capabilities = ["deny"]
}

path "auth/token/create*" {
  capabilities = ["deny"]
}
