# Generated by scripts/generate_workload_policies.py; do not hand-edit.
# Identity: middleware-worker; environment: staging; owner: middleware-platform

path "codestra/data/staging/middleware/worker/email/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/middleware/worker/email/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/staging/middleware/worker/sms/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/middleware/worker/sms/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/staging/middleware/worker/social/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/middleware/worker/social/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/staging/middleware/worker/advertising/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/middleware/worker/advertising/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/staging/middleware/worker/ai/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/middleware/worker/ai/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/staging/middleware/worker/telephony/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/middleware/worker/telephony/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/staging/middleware/worker/crawler/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/middleware/worker/crawler/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/development/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/development/*" {
  capabilities = ["deny"]
}

path "codestra/data/test/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/test/*" {
  capabilities = ["deny"]
}

path "codestra/data/production/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/production/*" {
  capabilities = ["deny"]
}

path "auth/token/lookup-self" {
  capabilities = ["read"]
}

path "auth/token/renew-self" {
  capabilities = ["update"]
}

path "auth/token/revoke-self" {
  capabilities = ["update"]
}

path "database/*" {
  capabilities = ["deny"]
}

path "pki-*" {
  capabilities = ["deny"]
}

path "transit-*" {
  capabilities = ["deny"]
}

path "sys/*" {
  capabilities = ["deny"]
}

path "auth/token/create*" {
  capabilities = ["deny"]
}
