# Generated by scripts/generate_workload_policies.py; do not hand-edit.
# Identity: n8n-automation; environment: staging; owner: automation-platform

path "codestra/data/staging/n8n/middleware-client/*" {
  capabilities = ["read"]
}

path "codestra/metadata/staging/n8n/middleware-client/*" {
  capabilities = ["read", "list"]
}

path "codestra/data/development/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/development/*" {
  capabilities = ["deny"]
}

path "codestra/data/test/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/test/*" {
  capabilities = ["deny"]
}

path "codestra/data/production/*" {
  capabilities = ["deny"]
}

path "codestra/metadata/production/*" {
  capabilities = ["deny"]
}

path "auth/token/lookup-self" {
  capabilities = ["read"]
}

path "auth/token/renew-self" {
  capabilities = ["update"]
}

path "auth/token/revoke-self" {
  capabilities = ["update"]
}

path "database/*" {
  capabilities = ["deny"]
}

path "pki-*" {
  capabilities = ["deny"]
}

path "transit-*" {
  capabilities = ["deny"]
}

path "sys/*" {
  capabilities = ["deny"]
}

path "auth/token/create*" {
  capabilities = ["deny"]
}
